name: "alpine"
concurrency: { group: "${{ github.workflow }}-${{ github.ref_type }}-${{ github.ref_name }}", cancel-in-progress: true }
permissions: 
  contents: read
  pull-requests: read
  packages: write

on:
  workflow_dispatch:
  schedule: [{ cron: "0 0 * * *" }]
  pull_request: { branches: [main], paths: ["alpine/*"] }
  push: { branches: [main], paths: ["alpine/*", ".github/actions/**.yml"] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - { name: checkout project., uses: actions/checkout@v3 }
      - { name: build., uses: ./.github/actions/docker-build }
  test:
    needs: [build]
    runs-on: ubuntu-latest
    container: "ghcr.io/${{ github.repository_owner }}/${{ github.workflow }}:latest"
    steps:
      - run: "apk update"
      - run: "apk list -I | sort"
