name: "ci"
concurrency: { group: "${{ github.workflow }}-${{ github.ref_type }}-${{ github.ref_name }}", cancel-in-progress: true }
permissions: 
  contents: read
  pull-requests: read
  packages: write

on:
  workflow_dispatch:
  
  schedule: [{ cron: "0 4 * * *" }]
  pull_request: { branches: [main], paths: ["ci/*", ".github/workflows/ci.yml"] }
  push: { branches: [main], paths: ["ci/*", ".github/workflows/ci.yml"] }

  workflow_run:  #whenever upstream image is rebuilt.
    workflows: ["alpine"]
    types: ["completed"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - { name: checkout project., uses: actions/checkout@v3 }
      - { name: build., uses: ./.github/actions/docker-build }

  test:
    needs: [build]
    runs-on: ubuntu-latest
    container: "ghcr.io/${{ github.repository_owner }}/${{ github.workflow }}:latest"
    steps:
      - run: "neofetch"
      - run: "apk update"
      - run: "apk list -I | sort"
