name: "nix"
concurrency: { group: "${{ github.workflow }}-${{ github.ref_type }}-${{ github.ref_name }}", cancel-in-progress: true }
permissions: 
  contents: read
  pull-requests: read
  packages: write

on:
  workflow_dispatch:
  schedule: [{ cron: "0 0 * * *" }]
  pull_request: { branches: [main], paths: ["nix/*"] }
  push: { branches: [main], paths: ["nix/*"] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - { name: checkout project., uses: actions/checkout@v3 }
      - { name: build., uses: ./.github/actions/docker-build }
