name: "perceval"
concurrency: { group: "${{ github.workflow }}-${{ github.ref_type }}-${{ github.ref_name }}", cancel-in-progress: true }
permissions: 
  contents: read
  pull-requests: read
  packages: write

on:
  workflow_dispatch:
  
  schedule: [{ cron: "0 4 * * *" }]
  pull_request: { branches: [main], paths: ["perceval/Dockerfile", ".github/workflows/perceval.yml"] }
  push: { branches: [main], paths: ["perceval/Dockerfile", ".github/workflows/perceval.yml"] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - { name: checkout project., uses: actions/checkout@v3 }
      - { name: build., uses: ./.github/actions/docker-build }

  test:
    needs: [build]
    runs-on: ubuntu-latest
    container: "ghcr.io/${{ github.repository_owner }}/${{ github.workflow }}:latest"
    steps:
      - run: "perceval --help"

